# Generated by Django 5.1.7 on 2025-03-11 21:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_price_and_quantity_to_oiltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('name', models.CharField(default='الحساب الرئيسي', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='notes',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='treasury',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='loading_location',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='oil_type',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='unloading_location',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='treasury',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='oil_capacity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='status',
        ),
        migrations.AddField(
            model_name='balancechangelog',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.driver'),
        ),
        migrations.AddField(
            model_name='driver',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد'),
        ),
        migrations.AddField(
            model_name='sale',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='TR-001', editable=False, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'دفع'), ('receipt', 'قبض')], default='payment', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.CharField(default='VH-001', editable=False, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='balancechangelog',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancechangelog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.client'),
        ),
        migrations.AlterField(
            model_name='balancechangelog',
            name='new_balance',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balancechangelog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancechangelog',
            name='previous_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='balancechangelog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='movement_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='رقم الحركة'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='movement_source',
            field=models.CharField(choices=[('client_account', 'حساب عميل'), ('company_account', 'حساب شركة'), ('driver_account', 'حساب سائق'), ('direct_deposit', 'إيداع مباشر')], max_length=20),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('check', 'شيك'), ('transfer', 'تحويل'), ('other', 'أخرى')], max_length=10),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'وارد'), ('expense', 'منصرف')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.driver'),
        ),
    ]
