# Generated by Django 5.1.7 on 2025-03-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyaccount_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
