# Generated by Django 5.1.7 on 2025-03-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_client_client_id_alter_driver_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='BU_ID',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
