# Generated by Django 5.1.7 on 2025-03-12 00:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sale_driver_sale_loading_location_sale_oil_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('user', 'Regular User'), ('client_manager', 'مدير العملاء'), ('reports_viewer', 'مشاهد التقارير')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='VehicleMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('movement_type', models.CharField(choices=[('internal', 'داخلي'), ('external', 'خارجي')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('loading_location', models.CharField(max_length=200)),
                ('unloading_location', models.CharField(max_length=200)),
                ('transportation_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='النولون')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.driver')),
                ('oil_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.oiltype')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.purchase')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.sale')),
            ],
            options={
                'verbose_name': 'حركة سيارة',
                'verbose_name_plural': 'حركات السيارات',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
