# Generated by Django 5.1.7 on 2025-03-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_vehicle_driver_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemovement',
            name='vehicle_number',
            field=models.CharField(default='', max_length=20, verbose_name='رقم السيارة'),
            preserve_default=False,
        ),
    ]