# Generated by Django 5.1.7 on 2025-03-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_vehiclemovement_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemovement',
            name='driver_freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='النولون للسائق'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclemovement',
            name='client_freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='النولون للعميل'),
            preserve_default=False,
        ),
    ]