# Generated by Django 5.1.7 on 2025-03-16 22:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_vehiclemovement_driver_freight_vehiclemovement_client_freight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclemovement',
            options={'ordering': ['-date'], 'verbose_name': 'حركة السيارة', 'verbose_name_plural': 'حركات السيارات'},
        ),
        migrations.RemoveField(
            model_name='vehiclemovement',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.client', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الحركة'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.driver', verbose_name='السائق'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='loading_location',
            field=models.CharField(max_length=200, verbose_name='مكان التحميل'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='movement_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='رقم الحركة'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='movement_type',
            field=models.CharField(choices=[('internal', 'داخلى'), ('external', 'خارجى')], max_length=10, verbose_name='نوع الحركة'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='oil_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.oiltype', verbose_name='نوع الزيت'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='unloading_location',
            field=models.CharField(max_length=200, verbose_name='مكان التفريغ'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
