# Generated by Django 5.1.7 on 2025-03-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_vehiclemovement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemovement',
            name='transportation_cost',
        ),
        migrations.AddField(
            model_name='purchase',
            name='vehicle_movements',
            field=models.ManyToManyField(blank=True, related_name='purchase_movements', to='accounts.vehiclemovement'),
        ),
        migrations.AddField(
            model_name='sale',
            name='vehicle_movements',
            field=models.ManyToManyField(blank=True, related_name='sale_movements', to='accounts.vehiclemovement'),
        ),
        migrations.AddField(
            model_name='vehiclemovement',
            name='operation_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم العملية'),
        ),
        migrations.AddField(
            model_name='vehiclemovement',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('sale', 'مبيعات'), ('purchase', 'مشتريات')], max_length=10, null=True, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الكمية بالطن'),
        ),
    ]
