# Generated by Django 5.1.7 on 2025-03-18 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_vehiclemovement_movement_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclemovement',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='vehiclemovement',
            name='operation_id',
        ),
        migrations.RemoveField(
            model_name='vehiclemovement',
            name='operation_type',
        ),
        migrations.RemoveField(
            model_name='vehiclemovement',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='vehiclemovement',
            name='sale',
        ),
        migrations.AddField(
            model_name='vehiclemovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='client_freight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.driver'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='driver_freight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='loading_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='movement_type',
            field=models.CharField(choices=[('internal', 'داخلية'), ('external', 'خارجية')], default='external', max_length=10, verbose_name='نوع الحركة'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='oil_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.oiltype'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='unloading_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='vehicle_number',
            field=models.CharField(max_length=20),
        ),
    ]
