# Generated by Django 5.1.7 on 2025-03-19 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_vehiclemovement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date'], 'verbose_name': 'عملية شراء', 'verbose_name_plural': 'عمليات الشراء'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date'], 'verbose_name': 'عملية بيع', 'verbose_name_plural': 'عمليات البيع'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemovement',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'حركة سيارة', 'verbose_name_plural': 'حركات السيارات'},
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='total',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='client',
            new_name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='vehicle_movements',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='vehicle_movements',
        ),
        migrations.AddField(
            model_name='purchase',
            name='client_freight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='driver_freight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='client_freight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='driver_freight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.driver'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='oil_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.oiltype'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='client_freight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='نولون العميل'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.driver', verbose_name='السائق'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='driver_freight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='نولون السائق'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='loading_location',
            field=models.CharField(max_length=100, verbose_name='مكان التحميل'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='oil_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.oiltype', verbose_name='نوع الزيت'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='unloading_location',
            field=models.CharField(max_length=100, verbose_name='مكان التفريغ'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='vehicle_number',
            field=models.CharField(max_length=20, verbose_name='رقم السيارة'),
        ),
    ]
